### ISSUE TITLE
how to classify custom text datasets?

### ISSUE THREAD

**Issue by frankxu2004** [HKUST-KnowComp/PathPredictionForTextClassification#3]
Thanks for the nice work and great code written. 

However, it seems that the currently provided datasets are already processed using some methods. It would be great if it supports custom datasets like given some texts and a hierarchy of labels.

Could you elaborate more on how do you generate the file xxx.esa500.depth1/2?

**Comment by seanliu96** [comment]
Please refer to "On Dataless Hierarchical Text Classification" to check the algorithm about ESA and how to generate such similar datasets. 
We use this code (https://github.com/yqsong/DatalessClassification) to generate such datasets.


> To replicate the experiments for AAAI14, prepare the data here:
> edu.illinois.cs.cogcomp.classification.hierarchy.run.preparedata.newsgroups
> and run the classification here:
> edu.illinois.cs.cogcomp.classification.hierarchy.run.ml.newsgroups

**Comment by seanliu96** [comment]
And this code (https://github.com/yqsong/DatalessClassification/tree/master/src/edu/illinois/cs/cogcomp/classification/hierarchy/run/sim) can be used to generate similarities.

**Comment by frankxu2004** [comment]
I see. So the files like `20newsgroups.esa500.depth1` are generated by edu/illinois/cs/cogcomp/classification/hierarchy/run/sim, right? Just to make sure...

**Comment by seanliu96** [comment]
Yes
